### ISSUE TITLE
Keyword args of method grako.parse, including rule_name, are forwarded to grako.compile

### ISSUE THREAD

**Issue by cairomax** [apalala/grako#1]
Call `grako.parse(grammar, text, rule_name=name)` fails because the grammar itself is parsed with the option `rule_name=name`.
Expected behaviour: keyword arguments are not forwarded to `grako.compile`.

**Comment by apalala** [comment]
Thanks @cairomax!

Would you mind using the [issue base at Bitbucket](https://bitbucket.org/neogeny/grako/issues) in the future?
